# Generated by Django 5.0.1 on 2024-02-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_salary_from_vacancy_salary_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_matter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
