# Generated by Django 5.0.1 on 2024-02-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_workformat_vacancy_work_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.workformat'),
        ),
    ]
