# Generated by Django 5.0.1 on 2024-02-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_employmenttype_vacancy_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.employmenttype'),
        ),
    ]
